"""HTML email + SMS templates for candidate and HR notifications."""


def consent_sms(name: str, consent_url: str) -> str:
    return (
        f"Hi {name}! You've applied for a role with us. "
        f"Please give your consent for a 15-min AI screening call: {consent_url} "
        f"Reply STOP to opt out."
    )


def rejection_email_html(name: str, role: str, company: str) -> tuple[str, str]:
    subject = f"Your application for {role} at {company}"
    html = f"""
<div style="font-family:Arial,sans-serif;max-width:600px;margin:auto;padding:24px">
  <h2 style="color:#1f2937">Application Update</h2>
  <p>Dear {name},</p>
  <p>Thank you for your interest in the <strong>{role}</strong> position at <strong>{company}</strong>.</p>
  <p>After carefully reviewing your profile, we have decided to move forward with candidates
  whose experience more closely matches our current requirements.</p>
  <p>We truly appreciate the time you invested in applying and wish you the very best in
  your job search.</p>
  <p>Best regards,<br><strong>The {company} Recruitment Team</strong></p>
</div>"""
    return subject, html


def interview_invite_email_html(name: str, role: str, company: str) -> tuple[str, str]:
    subject = f"You're shortlisted! AI Screening Call — {role} at {company}"
    html = f"""
<div style="font-family:Arial,sans-serif;max-width:600px;margin:auto;padding:24px">
  <h2 style="color:#16a34a">Congratulations, {name}!</h2>
  <p>Your application for <strong>{role}</strong> at <strong>{company}</strong> has been shortlisted.</p>
  <p>You will receive a phone call from our AI interviewer <strong>Alex</strong> shortly.
  The call takes approximately <strong>15–20 minutes</strong>.</p>
  <h3>Tips for the call:</h3>
  <ul>
    <li>Find a quiet place with good phone reception</li>
    <li>Have your resume nearby for reference</li>
    <li>Speak clearly and take your time — the AI will wait for you</li>
    <li>The interviewer will introduce itself as an AI at the start of the call</li>
  </ul>
  <p>Best regards,<br><strong>The {company} Recruitment Team</strong></p>
</div>"""
    return subject, html


def hr_report_email_html(
    candidate_name: str,
    role: str,
    overall_score: int,
    recommendation: str,
    reasoning: str,
    strengths: list,
    red_flags: list,
    next_round_questions: list,
    company: str,
) -> tuple[str, str]:
    subject = f"[Screening Report] {candidate_name} — {role} | {recommendation}"
    color_map = {
        "HIRE": "#16a34a",
        "SHORTLIST": "#2563eb",
        "HOLD": "#d97706",
        "REJECT": "#dc2626",
    }
    color = color_map.get(recommendation, "#6b7280")

    strengths_html = "".join(f"<li>{s}</li>" for s in (strengths or []))
    flags_html = "".join(f"<li>{f}</li>" for f in (red_flags or []))
    questions_html = "".join(f"<li>{q}</li>" for q in (next_round_questions or []))

    html = f"""
<div style="font-family:Arial,sans-serif;max-width:640px;margin:auto;padding:24px">
  <h2 style="color:#1f2937">Post-Screening Report</h2>
  <table style="width:100%;border-collapse:collapse;margin-bottom:16px">
    <tr><td style="padding:8px;font-weight:bold">Candidate</td><td>{candidate_name}</td></tr>
    <tr style="background:#f9fafb"><td style="padding:8px;font-weight:bold">Role</td><td>{role}</td></tr>
    <tr><td style="padding:8px;font-weight:bold">Overall Score</td><td><strong>{overall_score}/100</strong></td></tr>
    <tr style="background:#f9fafb">
      <td style="padding:8px;font-weight:bold">AI Recommendation</td>
      <td><span style="color:{color};font-weight:bold;font-size:16px">{recommendation}</span></td>
    </tr>
  </table>
  <h3>Reasoning</h3>
  <p style="color:#374151">{reasoning}</p>
  <h3 style="color:#16a34a">Strengths</h3>
  <ul>{strengths_html}</ul>
  <h3 style="color:#dc2626">Red Flags</h3>
  <ul>{flags_html if flags_html else "<li>None identified</li>"}</ul>
  <h3>Suggested Next-Round Questions</h3>
  <ul>{questions_html}</ul>
  <hr style="margin:24px 0">
  <p style="color:#6b7280;font-size:12px">
    Generated by {company} AI Hiring Bot. Review the full transcript in the HR dashboard.
  </p>
</div>"""
    return subject, html
